### ISSUE TITLE
flags != OP1_CLASS;  

### ISSUE THREAD

**Issue by jimmyleeeeee** [derickr/vld#64] opened 2020-07-15 08:27 UTC
In srm_oparray.c line 636,
  
flags != OP1_CLASS;

This is a comparison sentence. It is useless here.  Is it a mistake for flags |= OP1_CLASS; ?

**Comment by jimmyleeeeee** [comment] 2020-07-24 07:03
@derickr     Do you have time to confirm this issue? Thanks.

**Comment by derickr** [comment] 2020-07-24 08:56
Duplicate of #63, and also incorrect, as the line this is on is 598.

**Closed by derickr** 2020-07-24 08:56 UTC

**Comment by jimmyleeeeee** [comment] 2020-07-27 03:19
Thanks for the confirmation.
